-- Problem 2: Even Fibonacci Numbers

-- Each new term in the Fibonacci sequence is generated by adding the 
-- previous two terms. By starting with 1 and 2, the first 10 terms will be:
--                 1, 2, 3, 5, 8, ..
-- By considering the terms in the Fibonacci sequence whose values do 
-- not exceed four million, find the sum of the even-valued terms.

main = putStrLn $ show ans

ans = sum $ takeWhile (<=4000000) $ filter even fibSeq

fibSeq = 1:fib 1 1
  where fib x y = y:fib y (x + y)
